/* ================ INSERTS TABELAS ================ */


/* === TABELA CAD_PERIODOS === */

INSERT INTO CAD_PERIODOS 
(NOME, PERIODO_INICIO, PERIODO_FIM, EXCLUIDO)
VALUES
('Primeiro Trimestre 2020', CONVERT(DATETIME, '03/01/2020'), CONVERT(DATETIME, '05/31/2020'), 0)

GO

INSERT INTO CAD_PERIODOS 
(NOME, PERIODO_INICIO, PERIODO_FIM, EXCLUIDO)
VALUES
('Segundo Trimestre 2020', CONVERT(DATETIME, '06/01/2020'), CONVERT(DATETIME, '09/15/2020'), 0)

GO

INSERT INTO CAD_PERIODOS 
(NOME, PERIODO_INICIO, PERIODO_FIM, EXCLUIDO)
VALUES
('Terceiro Trimestre 2020', CONVERT(DATETIME, '09/16/2020'), CONVERT(DATETIME, '12/15/2020'), 0)

GO

/* === TABELA CAD_PERMISSOES === */

INSERT INTO CAD_PERMISSOES
(NOME, EXCLUIDO)
VALUES
('Admin', 0)

GO

INSERT INTO CAD_PERMISSOES
(NOME, EXCLUIDO)
VALUES
('Professor', 0)

GO

INSERT INTO CAD_PERMISSOES
(NOME, EXCLUIDO)
VALUES
('Aluno', 0)

GO

/* === TABELA CAD_DISCIPLINAS === */

INSERT INTO CAD_DISCIPLINAS
(NOME, EXCLUIDO)
VALUES
('Matemática', 0)

GO

INSERT INTO CAD_DISCIPLINAS
(NOME, EXCLUIDO)
VALUES
('Português', 0)

GO

INSERT INTO CAD_DISCIPLINAS
(NOME, EXCLUIDO)
VALUES
('Biologia', 0)

GO

INSERT INTO CAD_DISCIPLINAS
(NOME, EXCLUIDO)
VALUES
('Física', 0)

GO

INSERT INTO CAD_DISCIPLINAS
(NOME, EXCLUIDO)
VALUES
('Química', 0)

GO

INSERT INTO CAD_DISCIPLINAS
(NOME, EXCLUIDO)
VALUES
('Filosofia', 0)

GO

INSERT INTO CAD_DISCIPLINAS
(NOME, EXCLUIDO)
VALUES
('Geografia', 0)

GO

INSERT INTO CAD_DISCIPLINAS
(NOME, EXCLUIDO)
VALUES
('História', 0)

GO

INSERT INTO CAD_DISCIPLINAS
(NOME, EXCLUIDO)
VALUES
('Sociologia', 0)

GO

INSERT INTO CAD_DISCIPLINAS
(NOME, EXCLUIDO)
VALUES
('Educação Física', 0)

GO

INSERT INTO CAD_DISCIPLINAS
(NOME, EXCLUIDO)
VALUES
('Artes', 0)

GO

INSERT INTO CAD_DISCIPLINAS
(NOME, EXCLUIDO)
VALUES
('Língua Estrangeira', 0)

GO

INSERT INTO CAD_DISCIPLINAS
(NOME, EXCLUIDO)
VALUES
('Literatura', 0)

GO

/* === TABELA CAD_TURNOS === */

INSERT INTO CAD_TURNOS
(NOME, EXCLUIDO)
VALUES
('Manhã', 0)

GO

INSERT INTO CAD_TURNOS
(NOME, EXCLUIDO)
VALUES
('Tarde', 0)

GO

INSERT INTO CAD_TURNOS
(NOME, EXCLUIDO)
VALUES
('Noite', 0)

GO

/* === TABELA CAD_SERIES === */

INSERT INTO CAD_SERIES
(NOME, EXCLUIDO)
VALUES
('1° Série Ensino Fundamental', 0)

GO

INSERT INTO CAD_SERIES
(NOME, EXCLUIDO)
VALUES
('2° Série Ensino Fundamental', 0)

GO

INSERT INTO CAD_SERIES
(NOME, EXCLUIDO)
VALUES
('3° Série Ensino Fundamental', 0)

GO

INSERT INTO CAD_SERIES
(NOME, EXCLUIDO)
VALUES
('4° Série Ensino Fundamental', 0)

GO

INSERT INTO CAD_SERIES
(NOME, EXCLUIDO)
VALUES
('5° Série Ensino Fundamental', 0)

GO

INSERT INTO CAD_SERIES
(NOME, EXCLUIDO)
VALUES
('6° Série Ensino Fundamental', 0)

GO

INSERT INTO CAD_SERIES
(NOME, EXCLUIDO)
VALUES
('7° Série Ensino Fundamental', 0)

GO

INSERT INTO CAD_SERIES
(NOME, EXCLUIDO)
VALUES
('8° Série Ensino Fundamental', 0)

GO

INSERT INTO CAD_SERIES
(NOME, EXCLUIDO)
VALUES
('9° Série Ensino Fundamental', 0)

GO

INSERT INTO CAD_SERIES
(NOME, EXCLUIDO)
VALUES
('1° Ano Ensino Médio', 0)

GO

INSERT INTO CAD_SERIES
(NOME, EXCLUIDO)
VALUES
('2° Ano Ensino Médio', 0)

GO

INSERT INTO CAD_SERIES
(NOME, EXCLUIDO)
VALUES
('3° Ano Ensino Médio', 0)

GO

/* === TABELA CAD_PERFIS === */

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('admin', 'admin', 1, 'Admin - Diretoria', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Alice', 'Alice', 3, 'Alice', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Miguel', 'Miguel', 3, 'Miguel', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Sophia', 'Sophia', 3, 'Sophia', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Arthur', 'Arthur', 3, 'Arthur', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Helena', 'Helena', 3, 'Helena', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Bernardo', 'Bernardo', 3, 'Bernardo', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Valentina', 'Valentina', 3, 'Valentina', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Heitor', 'Heitor', 3, 'Heitor', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Laura', 'Laura', 3, 'Laura', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Davi', 'Davi', 3, 'Davi', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Isabella', 'Isabella', 3, 'Isabella', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Lorenzo', 'Lorenzo', 3, 'Lorenzo', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Manuela', 'Manuela', 3, 'Manuela', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Théo', 'Théo', 3, 'Théo', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Júlia', 'Júlia', 3, 'Júlia', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Pedro', 'Pedro', 3, 'Pedro', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Heloísa', 'Heloísa', 3, 'Heloísa', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Gabriel', 'Gabriel', 3, 'Gabriel', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Luiza', 'Luiza', 3, 'Luiza', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Enzo', 'Enzo', 3, 'Enzo', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Maria_Luiza', 'Maria_Luiza', 3, 'Maria_Luiza', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Matheus', 'Matheus', 3, 'Matheus', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Lorena', 'Lorena', 3, 'Lorena', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Lucas', 'Lucas', 3, 'Lucas', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Lívia', 'Lívia', 3, 'Lívia', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Benjamin', 'Benjamin', 3, 'Benjamin', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Giovanna', 'Giovanna', 3, 'Giovanna', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Nicolas', 'Nicolas', 3, 'Nicolas', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Maria_Eduarda', 'Maria_Eduarda', 3, 'Maria_Eduarda', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Guilherme', 'Guilherme', 3, 'Guilherme', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Beatriz', 'Beatriz', 3, 'Beatriz', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Rafael', 'Rafael', 3, 'Rafael', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Maria_Clara', 'Maria_Clara', 3, 'Maria_Clara', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Joaquim', 'Joaquim', 3, 'Joaquim', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Cecília', 'Cecília', 3, 'Cecília', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Samuel', 'Samuel', 3, 'Samuel', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Eloá', 'Eloá', 3, 'Eloá', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Enzo_Gabriel', 'Enzo_Gabriel', 3, 'Enzo_Gabriel', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Lara', 'Lara', 3, 'Lara', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('João_Miguel', 'João_Miguel', 3, 'João_Miguel', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Maria_Júlia', 'Maria_Júlia', 3, 'Maria_Júlia', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Henrique', 'Henrique', 3, 'Henrique', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Isadora', 'Isadora', 3, 'Isadora', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Gustavo', 'Gustavo', 3, 'Gustavo', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Mariana', 'Mariana', 3, 'Mariana', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Murilo', 'Murilo', 3, 'Murilo', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Emanuelly', 'Emanuelly', 3, 'Emanuelly', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Pedro_Henrique', 'Pedro_Henrique', 3, 'Pedro_Henrique', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Ana_Júlia', 'Ana_Júlia', 3, 'Ana_Júlia', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Pietro', 'Pietro', 3, 'Pietro', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Ana_Luiza', 'Ana_Luiza', 3, 'Ana_Luiza', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Lucca', 'Lucca', 3, 'Lucca', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Ana_Clara', 'Ana_Clara', 3, 'Ana_Clara', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Felipe', 'Felipe', 3, 'Felipe', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Melissa', 'Melissa', 3, 'Melissa', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('João_Pedro', 'João_Pedro', 3, 'João_Pedro', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Yasmin', 'Yasmin', 3, 'Yasmin', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Isaac', 'Isaac', 3, 'Isaac', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Maria_Alice', 'Maria_Alice', 3, 'Maria_Alice', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Benício', 'Benício', 3, 'Benício', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Isabelly', 'Isabelly', 3, 'Isabelly', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Daniel', 'Daniel', 3, 'Daniel', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Lavínia', 'Lavínia', 3, 'Lavínia', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Anthony', 'Anthony', 3, 'Anthony', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Esther', 'Esther', 3, 'Esther', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Leonardo', 'Leonardo', 3, 'Leonardo', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Sarah', 'Sarah', 3, 'Sarah', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Davi_Lucca', 'Davi_Lucca', 3, 'Davi_Lucca', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Elisa', 'Elisa', 3, 'Elisa', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Bryan', 'Bryan', 3, 'Bryan', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Antonella', 'Antonella', 3, 'Antonella', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Eduardo', 'Eduardo', 3, 'Eduardo', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Rafaela', 'Rafaela', 3, 'Rafaela', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('João_Lucas', 'João_Lucas', 3, 'João_Lucas', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Maria_Cecília', 'Maria_Cecília', 3, 'Maria_Cecília', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Victor', 'Victor', 3, 'Victor', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Liz', 'Liz', 3, 'Liz', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('João', 'João', 3, 'João', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Marina', 'Marina', 3, 'Marina', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Cauã', 'Cauã', 3, 'Cauã', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Nicole', 'Nicole', 3, 'Nicole', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Antônio', 'Antônio', 3, 'Antônio', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Maitê', 'Maitê', 3, 'Maitê', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Vicente', 'Vicente', 3, 'Vicente', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Isis', 'Isis', 3, 'Isis', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Caleb', 'Caleb', 3, 'Caleb', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Alícia', 'Alícia', 3, 'Alícia', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Gael', 'Gael', 3, 'Gael', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Luna', 'Luna', 3, 'Luna', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Bento', 'Bento', 3, 'Bento', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Rebeca', 'Rebeca', 3, 'Rebeca', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Caio', 'Caio', 3, 'Caio', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Agatha', 'Agatha', 3, 'Agatha', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Emanuel', 'Emanuel', 3, 'Emanuel', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Letícia', 'Letícia', 3, 'Letícia', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Vinícius', 'Vinícius', 3, 'Vinícius', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Maria', 'Maria', 3, 'Maria', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('João_Guilherme', 'João_Guilherme', 3, 'João_Guilherme', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Gabriela', 'Gabriela', 3, 'Gabriela', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Davi_Lucas', 'Davi_Lucas', 3, 'Davi_Lucas', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Ana_Laura', 'Ana_Laura', 3, 'Ana_Laura', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Noah', 'Noah', 3, 'Noah', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Catarina', 'Catarina', 3, 'Catarina', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('João_Gabriel', 'João_Gabriel', 3, 'João_Gabriel', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Clara', 'Clara', 3, 'Clara', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('João_Victor', 'João_Victor', 3, 'João_Victor', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Ana_Beatriz', 'Ana_Beatriz', 3, 'Ana_Beatriz', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Luiz_Miguel', 'Luiz_Miguel', 3, 'Luiz_Miguel', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Vitória', 'Vitória', 3, 'Vitória', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Francisco', 'Francisco', 3, 'Francisco', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Olívia', 'Olívia', 3, 'Olívia', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Kaique', 'Kaique', 3, 'Kaique', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Maria_Fernanda', 'Maria_Fernanda', 3, 'Maria_Fernanda', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Otávio', 'Otávio', 3, 'Otávio', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Emilly', 'Emilly', 3, 'Emilly', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Augusto', 'Augusto', 3, 'Augusto', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Maria_Valentina', 'Maria_Valentina', 3, 'Maria_Valentina', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Levi', 'Levi', 3, 'Levi', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Milena', 'Milena', 3, 'Milena', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Yuri', 'Yuri', 3, 'Yuri', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Maria_Helena', 'Maria_Helena', 3, 'Maria_Helena', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Enrico', 'Enrico', 3, 'Enrico', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Bianca', 'Bianca', 3, 'Bianca', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Thiago', 'Thiago', 3, 'Thiago', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Larissa', 'Larissa', 3, 'Larissa', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Ian', 'Ian', 3, 'Ian', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Mirella', 'Mirella', 3, 'Mirella', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Victor_Hugo', 'Victor_Hugo', 3, 'Victor_Hugo', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Maria_Flor', 'Maria_Flor', 3, 'Maria_Flor', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Thomas', 'Thomas', 3, 'Thomas', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Allana', 'Allana', 3, 'Allana', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Henry', 'Henry', 3, 'Henry', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Ana_Sophia', 'Ana_Sophia', 3, 'Ana_Sophia', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Luiz_Felipe', 'Luiz_Felipe', 3, 'Luiz_Felipe', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Clarice', 'Clarice', 3, 'Clarice', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Ryan', 'Ryan', 3, 'Ryan', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Pietra', 'Pietra', 3, 'Pietra', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Arthur_Miguel', 'Arthur_Miguel', 3, 'Arthur_Miguel', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Maria_Vitória', 'Maria_Vitória', 3, 'Maria_Vitória', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Davi_Luiz', 'Davi_Luiz', 3, 'Davi_Luiz', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Maya', 'Maya', 3, 'Maya', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Nathan', 'Nathan', 3, 'Nathan', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Laís', 'Laís', 3, 'Laís', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Pedro_Lucas', 'Pedro_Lucas', 3, 'Pedro_Lucas', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Ayla', 'Ayla', 3, 'Ayla', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Davi_Miguel', 'Davi_Miguel', 3, 'Davi_Miguel', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Ana_Lívia', 'Ana_Lívia', 3, 'Ana_Lívia', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Raul', 'Raul', 3, 'Raul', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Eduarda', 'Eduarda', 3, 'Eduarda', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Pedro_Miguel', 'Pedro_Miguel', 3, 'Pedro_Miguel', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Mariah', 'Mariah', 3, 'Mariah', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Luiz_Henrique', 'Luiz_Henrique', 3, 'Luiz_Henrique', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Stella', 'Stella', 3, 'Stella', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Luan', 'Luan', 3, 'Luan', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Ana', 'Ana', 3, 'Ana', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Erick', 'Erick', 3, 'Erick', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Gabrielly', 'Gabrielly', 3, 'Gabrielly', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Martin', 'Martin', 3, 'Martin', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Sophie', 'Sophie', 3, 'Sophie', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Bruno', 'Bruno', 3, 'Bruno', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Carolina', 'Carolina', 3, 'Carolina', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Rodrigo', 'Rodrigo', 3, 'Rodrigo', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Maria_Laura', 'Maria_Laura', 3, 'Maria_Laura', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Luiz_Gustavo', 'Luiz_Gustavo', 3, 'Luiz_Gustavo', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Maria_Heloísa', 'Maria_Heloísa', 3, 'Maria_Heloísa', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Arthur_Gabriel', 'Arthur_Gabriel', 3, 'Arthur_Gabriel', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Maria_Sophia', 'Maria_Sophia', 3, 'Maria_Sophia', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Breno', 'Breno', 3, 'Breno', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Fernanda', 'Fernanda', 3, 'Fernanda', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Kauê', 'Kauê', 3, 'Kauê', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Malu', 'Malu', 3, 'Malu', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Enzo_Miguel', 'Enzo_Miguel', 3, 'Enzo_Miguel', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Analu', 'Analu', 3, 'Analu', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Fernando', 'Fernando', 3, 'Fernando', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Amanda', 'Amanda', 3, 'Amanda', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Arthur_Henrique', 'Arthur_Henrique', 3, 'Arthur_Henrique', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Aurora', 'Aurora', 3, 'Aurora', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Luiz_Otávio', 'Luiz_Otávio', 3, 'Luiz_Otávio', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Maria_Isis', 'Maria_Isis', 3, 'Maria_Isis', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Carlos_Eduardo', 'Carlos_Eduardo', 3, 'Carlos_Eduardo', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Louise', 'Louise', 3, 'Louise', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Tomás', 'Tomás', 3, 'Tomás', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Heloise', 'Heloise', 3, 'Heloise', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Lucas_Gabriel', 'Lucas_Gabriel', 3, 'Lucas_Gabriel', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Ana_Vitória', 'Ana_Vitória', 3, 'Ana_Vitória', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('André', 'André', 3, 'André', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Ana_Cecília', 'Ana_Cecília', 3, 'Ana_Cecília', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('José', 'José', 3, 'José', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Ana_Liz', 'Ana_Liz', 3, 'Ana_Liz', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Yago', 'Yago', 3, 'Yago', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Joana', 'Joana', 3, 'Joana', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Danilo', 'Danilo', 3, 'Danilo', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Luana', 'Luana', 3, 'Luana', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Anthony_Gabriel', 'Anthony_Gabriel', 3, 'Anthony_Gabriel', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Antônia', 'Antônia', 3, 'Antônia', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Ruan', 'Ruan', 3, 'Ruan', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Isabel', 'Isabel', 3, 'Isabel', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Miguel_Henrique', 'Miguel_Henrique', 3, 'Miguel_Henrique', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Bruna', 'Bruna', 3, 'Bruna', 0)

GO

INSERT INTO CAD_PERFIS
(LOGIN, SENHA, IDPERMISSAO, NOME, EXCLUIDO)
VALUES
('Oliver', 'Oliver', 3, 'Oliver', 0)

GO

/* === TABELA CAD_TURMAS === */


INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T1-A', 1, 1, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T1-B', 1, 1, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T1-C', 1, 1, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T1-D', 1, 2, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T1-E', 1, 2, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T1-F', 1, 2, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T1-G', 1, 3, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T1-H', 1, 3, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T1-I', 1, 3, 0)

GO


INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T2-A', 2, 1, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T2-B', 2, 1, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T2-C', 2, 1, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T2-D', 2, 2, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T2-E', 2, 2, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T2-F', 2, 2, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T2-G', 2, 3, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T2-H', 2, 3, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T2-I', 2, 3, 0)

GO


INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T3-A', 3, 1, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T3-B', 3, 1, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T3-C', 3, 1, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T3-D', 3, 2, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T3-E', 3, 2, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T3-F', 3, 2, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T3-G', 3, 3, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T3-H', 3, 3, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T3-I', 3, 3, 0)

GO


INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T4-A', 4, 1, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T4-B', 4, 1, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T4-C', 4, 1, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T4-D', 4, 2, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T4-E', 4, 2, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T4-F', 4, 2, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T4-G', 4, 3, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T4-H', 4, 3, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T4-I', 4, 3, 0)

GO


INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T5-A', 5, 1, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T5-B', 5, 1, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T5-C', 5, 1, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T5-D', 5, 2, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T5-E', 5, 2, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T5-F', 5, 2, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T5-G', 5, 3, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T5-H', 5, 3, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T5-I', 5, 3, 0)

GO


INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T6-A', 6, 1, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T6-B', 6, 1, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T6-C', 6, 1, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T6-D', 6, 2, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T6-E', 6, 2, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T6-F', 6, 2, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T6-G', 6, 3, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T6-H', 6, 3, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T6-I', 6, 3, 0)

GO


INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T7-A', 7, 1, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T7-B', 7, 1, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T7-C', 7, 1, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T7-D', 7, 2, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T7-E', 7, 2, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T7-F', 7, 2, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T7-G', 7, 3, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T7-H', 7, 3, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T7-I', 7, 3, 0)

GO


INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T8-A', 8, 1, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T8-B', 8, 1, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T8-C', 8, 1, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T8-D', 8, 2, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T8-E', 8, 2, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T8-F', 8, 2, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T8-G', 8, 3, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T8-H', 8, 3, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T8-I', 8, 3, 0)

GO


INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T9-A', 9, 1, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T9-B', 9, 1, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T9-C', 9, 1, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T9-D', 9, 2, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T9-E', 9, 2, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T9-F', 9, 2, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T9-G', 9, 3, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T9-H', 9, 3, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T9-I', 9, 3, 0)

GO


INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T11-A', 10, 1, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T11-B', 10, 1, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T11-C', 10, 1, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T11-D', 10, 2, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T11-E', 10, 2, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T11-F', 10, 2, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T11-G', 10, 3, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T11-H', 10, 3, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T11-I', 10, 3, 0)

GO


INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T12-A', 11, 1, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T12-B', 11, 1, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T12-C', 11, 1, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T12-D', 11, 2, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T12-E', 11, 2, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T12-F', 11, 2, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T12-G', 11, 3, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T12-H', 11, 3, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T12-I', 11, 3, 0)

GO


INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T13-A', 12, 1, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T13-B', 12, 1, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T13-C', 12, 1, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T13-D', 12, 2, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T13-E', 12, 2, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T13-F', 12, 2, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T13-G', 12, 3, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T13-H', 12, 3, 0)

GO

INSERT INTO CAD_TURMAS
(NOME, IDSERIE, IDTURNO, EXCLUIDO)
VALUES
('T13-I', 12, 3, 0)

GO

/* === TABELA CAD_PROFESSORES === */

INSERT INTO CAD_PROFESSORES
(IDPERFIL, EXCLUIDO)
VALUES
(2, 0)

GO

INSERT INTO CAD_PROFESSORES
(IDPERFIL, EXCLUIDO)
VALUES
(3, 0)

GO

INSERT INTO CAD_PROFESSORES
(IDPERFIL, EXCLUIDO)
VALUES
(4, 0)

GO

INSERT INTO CAD_PROFESSORES
(IDPERFIL, EXCLUIDO)
VALUES
(5, 0)

GO

INSERT INTO CAD_PROFESSORES
(IDPERFIL, EXCLUIDO)
VALUES
(6, 0)

GO

INSERT INTO CAD_PROFESSORES
(IDPERFIL, EXCLUIDO)
VALUES
(7, 0)

GO

INSERT INTO CAD_PROFESSORES
(IDPERFIL, EXCLUIDO)
VALUES
(8, 0)

GO

INSERT INTO CAD_PROFESSORES
(IDPERFIL, EXCLUIDO)
VALUES
(9, 0)

GO

INSERT INTO CAD_PROFESSORES
(IDPERFIL, EXCLUIDO)
VALUES
(10, 0)

GO

INSERT INTO CAD_PROFESSORES
(IDPERFIL, EXCLUIDO)
VALUES
(11, 0)

GO

INSERT INTO CAD_PROFESSORES
(IDPERFIL, EXCLUIDO)
VALUES
(12, 0)

GO

INSERT INTO CAD_PROFESSORES
(IDPERFIL, EXCLUIDO)
VALUES
(13, 0)

GO

INSERT INTO CAD_PROFESSORES
(IDPERFIL, EXCLUIDO)
VALUES
(14, 0)

GO

INSERT INTO CAD_PROFESSORES
(IDPERFIL, EXCLUIDO)
VALUES
(15, 0)

GO

INSERT INTO CAD_PROFESSORES
(IDPERFIL, EXCLUIDO)
VALUES
(16, 0)

GO

INSERT INTO CAD_PROFESSORES
(IDPERFIL, EXCLUIDO)
VALUES
(17, 0)

GO

INSERT INTO CAD_PROFESSORES
(IDPERFIL, EXCLUIDO)
VALUES
(18, 0)

GO

INSERT INTO CAD_PROFESSORES
(IDPERFIL, EXCLUIDO)
VALUES
(19, 0)

GO

INSERT INTO CAD_PROFESSORES
(IDPERFIL, EXCLUIDO)
VALUES
(20, 0)

GO

INSERT INTO CAD_PROFESSORES
(IDPERFIL, EXCLUIDO)
VALUES
(21, 0)

GO

INSERT INTO CAD_PROFESSORES
(IDPERFIL, EXCLUIDO)
VALUES
(22, 0)

GO

INSERT INTO CAD_PROFESSORES
(IDPERFIL, EXCLUIDO)
VALUES
(23, 0)

GO

INSERT INTO CAD_PROFESSORES
(IDPERFIL, EXCLUIDO)
VALUES
(24, 0)

GO

INSERT INTO CAD_PROFESSORES
(IDPERFIL, EXCLUIDO)
VALUES
(25, 0)

GO

INSERT INTO CAD_PROFESSORES
(IDPERFIL, EXCLUIDO)
VALUES
(26, 0)

GO

INSERT INTO CAD_PROFESSORES
(IDPERFIL, EXCLUIDO)
VALUES
(27, 0)

GO

INSERT INTO CAD_PROFESSORES
(IDPERFIL, EXCLUIDO)
VALUES
(28, 0)

GO

INSERT INTO CAD_PROFESSORES
(IDPERFIL, EXCLUIDO)
VALUES
(29, 0)

GO

INSERT INTO CAD_PROFESSORES
(IDPERFIL, EXCLUIDO)
VALUES
(30, 0)

GO

INSERT INTO CAD_PROFESSORES
(IDPERFIL, EXCLUIDO)
VALUES
(31, 0)

GO

INSERT INTO CAD_PROFESSORES
(IDPERFIL, EXCLUIDO)
VALUES
(32, 0)

GO

INSERT INTO CAD_PROFESSORES
(IDPERFIL, EXCLUIDO)
VALUES
(33, 0)

GO

INSERT INTO CAD_PROFESSORES
(IDPERFIL, EXCLUIDO)
VALUES
(34, 0)

GO

INSERT INTO CAD_PROFESSORES
(IDPERFIL, EXCLUIDO)
VALUES
(35, 0)

GO

INSERT INTO CAD_PROFESSORES
(IDPERFIL, EXCLUIDO)
VALUES
(36, 0)

GO

INSERT INTO CAD_PROFESSORES
(IDPERFIL, EXCLUIDO)
VALUES
(37, 0)

GO

INSERT INTO CAD_PROFESSORES
(IDPERFIL, EXCLUIDO)
VALUES
(38, 0)

GO

INSERT INTO CAD_PROFESSORES
(IDPERFIL, EXCLUIDO)
VALUES
(39, 0)

GO

INSERT INTO CAD_PROFESSORES
(IDPERFIL, EXCLUIDO)
VALUES
(40, 0)

GO

INSERT INTO CAD_PROFESSORES
(IDPERFIL, EXCLUIDO)
VALUES
(41, 0)

GO

INSERT INTO CAD_PROFESSORES
(IDPERFIL, EXCLUIDO)
VALUES
(42, 0)

GO

INSERT INTO CAD_PROFESSORES
(IDPERFIL, EXCLUIDO)
VALUES
(43, 0)

GO

INSERT INTO CAD_PROFESSORES
(IDPERFIL, EXCLUIDO)
VALUES
(44, 0)

GO

INSERT INTO CAD_PROFESSORES
(IDPERFIL, EXCLUIDO)
VALUES
(45, 0)

GO

INSERT INTO CAD_PROFESSORES
(IDPERFIL, EXCLUIDO)
VALUES
(46, 0)

GO

INSERT INTO CAD_PROFESSORES
(IDPERFIL, EXCLUIDO)
VALUES
(47, 0)

GO

INSERT INTO CAD_PROFESSORES
(IDPERFIL, EXCLUIDO)
VALUES
(48, 0)

GO

INSERT INTO CAD_PROFESSORES
(IDPERFIL, EXCLUIDO)
VALUES
(49, 0)

GO

INSERT INTO CAD_PROFESSORES
(IDPERFIL, EXCLUIDO)
VALUES
(50, 0)

GO

INSERT INTO CAD_PROFESSORES
(IDPERFIL, EXCLUIDO)
VALUES
(51, 0)

GO



--V CAD_PERFIS
--  CAD_ALUNOS
--V CAD_PROFESSORES
--V CAD_SERIES
--V CAD_TURNOS
--V CAD_TURMAS
--V CAD_DISCIPLINAS
--V CAD_PERMISSOES
--V CAD_PERIODOS
--  CAD_NOTAS
--  REL_TURMAS__DISCIPLINAS