/* ================ CREATE TABELAS ================ */


/* === TABELA CAD_PERFIS === */

CREATE TABLE CAD_PERFIS
(
	IDPERFIL BIGINT NOT NULL IDENTITY(1, 1),
	LOGIN VARCHAR(15) NOT NULL,
	SENHA VARCHAR(30) NOT NULL,
	IDPERMISSAO INT NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	IDADE INT NULL,
	CPF VARCHAR(30) NULL,
	SEXO CHAR NULL,
	ENDERECO VARCHAR(100) NULL,
	TELEFONE_FIXO VARCHAR(50) NULL,
	TELEFONE_CELULAR VARCHAR(50) NULL,
	NOME_MAE VARCHAR(50) NULL,
	NOME_PAI VARCHAR(50) NULL,
	EXCLUIDO BIT NULL
)

GO

/* === TABELA CAD_ALUNOS === */

CREATE TABLE CAD_ALUNOS
(
	IDALUNO BIGINT NOT NULL IDENTITY(1,1),
	IDPERFIL BIGINT NOT NULL,
	IDTURMA INT NULL,
	EXCLUIDO BIT NULL
)

GO

/* === TABELA CAD_PROFESSORES === */

CREATE TABLE CAD_PROFESSORES
(
	IDPROFESSOR BIGINT NOT NULL IDENTITY(1,1),
	IDPERFIL BIGINT NOT NULL,
	EXCLUIDO BIT NULL
)

GO

/* === TABELA CAD_SERIES === */

CREATE TABLE CAD_SERIES
(
	IDSERIE INT NOT NULL IDENTITY(1, 1),
	NOME VARCHAR(30) NOT NULL,
	EXCLUIDO BIT NULL
)

GO

/* === TABELA CAD_TURNOS === */

CREATE TABLE CAD_TURNOS
(
	IDTURNO INT NOT NULL IDENTITY(1, 1),
	NOME VARCHAR(30) NOT NULL,
	EXCLUIDO BIT NULL
)

GO

/* === TABELA CAD_TURMAS === */

CREATE TABLE CAD_TURMAS
(
	IDTURMA INT NOT NULL IDENTITY(1, 1),
	NOME VARCHAR(30) NOT NULL,
	IDSERIE INT NULL,
	IDTURNO INT NULL,
	EXCLUIDO BIT NULL
)

GO

/* === TABELA CAD_DISCIPLINAS === */

CREATE TABLE CAD_DISCIPLINAS
(
	IDDISCIPLINA INT NOT NULL IDENTITY(1, 1),
	NOME VARCHAR(30) NOT NULL,
	EXCLUIDO BIT NULL
)

GO

/* === TABELA CAD_PERMISSOES === */

CREATE TABLE CAD_PERMISSOES
(
	IDPERMISSAO INT NOT NULL IDENTITY(1, 1),
	NOME VARCHAR(30) NOT NULL,
	EXCLUIDO BIT NULL
)

GO

/* === TABELA CAD_PERIODOS === */

CREATE TABLE CAD_PERIODOS
(
	IDPERIODO BIGINT NOT NULL IDENTITY(1, 1),
	NOME VARCHAR(30) NOT NULL,
	PERIODO_INICIO DATETIME NOT NULL,
	PERIODO_FIM DATETIME NOT NULL,
	EXCLUIDO BIT NULL
)

GO

/* === TABELA CAD_NOTAS === */

CREATE TABLE CAD_NOTAS
(
	IDNOTA BIGINT NOT NULL IDENTITY(1, 1),
	IDALUNO BIGINT NOT NULL,
	IDDISCIPLINA INT NOT NULL,
	IDPROFESSOR BIGINT NOT NULL,
	IDPERIODO BIGINT NOT NULL,
	EXCLUIDO BIT NULL
)

GO

/* === TABELA REL_TURMAS__DISCIPLINAS === */

CREATE TABLE REL_TURMAS__DISCIPLINAS
(
	IDTURMASDISCIPLINAS BIGINT NOT NULL IDENTITY(1, 1),
	IDTURMA INT NOT NULL,
	IDDISCIPLINA INT NOT NULL,
	IDPROFESSOR BIGINT NULL,
	EXCLUIDO BIT NULL
)

GO
