/* ================ CREATE UKS ================ */


/* === TABELA CAD_PERFIS === */

ALTER TABLE CAD_PERFIS ADD CONSTRAINT UK_CAD_PERFIS UNIQUE (CPF, LOGIN);

GO

/* === TABELA CAD_ALUNOS === */

ALTER TABLE CAD_ALUNOS ADD CONSTRAINT UK_CAD_ALUNOS UNIQUE (IDPERFIL);

GO

/* === TABELA CAD_PROFESSORES === */

ALTER TABLE CAD_PROFESSORES ADD CONSTRAINT UK_CAD_PROFESSORES UNIQUE (IDPERFIL);

GO

/* === TABELA CAD_SERIES === */

ALTER TABLE CAD_SERIES ADD CONSTRAINT UK_CAD_SERIES UNIQUE (NOME);

GO

/* === TABELA CAD_TURNOS === */

ALTER TABLE CAD_TURNOS ADD CONSTRAINT UK_CAD_TURNOS UNIQUE (NOME);

GO

/* === TABELA CAD_TURMAS === */

ALTER TABLE CAD_TURMAS ADD CONSTRAINT UK_CAD_TURMAS UNIQUE (NOME);

GO

/* === TABELA CAD_DISCIPLINAS === */

ALTER TABLE CAD_DISCIPLINAS ADD CONSTRAINT UK_CAD_DISCIPLINAS UNIQUE (NOME);

GO

/* === TABELA CAD_PERMISSOES === */

ALTER TABLE CAD_PERMISSOES ADD CONSTRAINT UK_CAD_PERMISSOES UNIQUE (NOME);

GO

/* === TABELA CAD_PERIODOS === */

ALTER TABLE CAD_PERIODOS ADD CONSTRAINT UK_CAD_PERIODOS UNIQUE (PERIODO_INICIO, PERIODO_FIM);

GO
