/* ================ CREATE FKS ================ */

/* === TABELA CAD_ALUNOS === */

ALTER TABLE CAD_PERFIS ADD CONSTRAINT FK_CAD_PERFIS_IDPERMISSAO FOREIGN KEY (IDPERMISSAO) REFERENCES CAD_PERMISSOES(IDPERMISSAO);

GO

/* === TABELA CAD_ALUNOS === */

ALTER TABLE CAD_ALUNOS ADD CONSTRAINT FK_CAD_ALUNOS_IDPERFIL FOREIGN KEY (IDPERFIL) REFERENCES CAD_PERFIS(IDPERFIL);

ALTER TABLE CAD_ALUNOS ADD CONSTRAINT FK_CAD_ALUNOS_IDTURMA FOREIGN KEY (IDTURMA) REFERENCES CAD_TURMAS(IDTURMA);

GO

/* === TABELA CAD_PROFESSORES === */

ALTER TABLE CAD_PROFESSORES ADD CONSTRAINT FK_CAD_PROFESSORES_IDPERFIL FOREIGN KEY (IDPERFIL) REFERENCES CAD_PERFIS(IDPERFIL);

GO

/* === TABELA CAD_TURMAS === */

ALTER TABLE CAD_TURMAS ADD CONSTRAINT FK_CAD_TURMAS_IDSERIE FOREIGN KEY (IDSERIE) REFERENCES CAD_SERIES(IDSERIE);

ALTER TABLE CAD_TURMAS ADD CONSTRAINT FK_CAD_TURMAS_IDTURNO FOREIGN KEY (IDTURNO) REFERENCES CAD_TURNOS(IDTURNO);

GO

/* === TABELA CAD_NOTAS === */

ALTER TABLE CAD_NOTAS ADD CONSTRAINT FK_CAD_NOTAS_IDALUNO FOREIGN KEY (IDALUNO) REFERENCES CAD_ALUNOS(IDALUNO);

ALTER TABLE CAD_NOTAS ADD CONSTRAINT FK_CAD_NOTAS_IDDISCIPLINA FOREIGN KEY (IDDISCIPLINA) REFERENCES CAD_DISCIPLINAS(IDDISCIPLINA);

ALTER TABLE CAD_NOTAS ADD CONSTRAINT FK_CAD_NOTAS_IDPROFESSOR FOREIGN KEY (IDPROFESSOR) REFERENCES CAD_PROFESSORES(IDPROFESSOR);

ALTER TABLE CAD_NOTAS ADD CONSTRAINT FK_CAD_NOTAS_IDPERIODO FOREIGN KEY (IDPERIODO) REFERENCES CAD_PERIODOS(IDPERIODO);

GO

/* === TABELA REL_TURMAS__DISCIPLINAS === */

ALTER TABLE REL_TURMAS__DISCIPLINAS ADD CONSTRAINT FK_REL_TURMAS__DISCIPLINAS_IDTURMA FOREIGN KEY (IDTURMA) REFERENCES CAD_TURMAS(IDTURMA);

ALTER TABLE REL_TURMAS__DISCIPLINAS ADD CONSTRAINT FK_REL_TURMAS__DISCIPLINAS_IDDISCIPLINA FOREIGN KEY (IDDISCIPLINA) REFERENCES CAD_DISCIPLINAS(IDDISCIPLINA);

ALTER TABLE REL_TURMAS__DISCIPLINAS ADD CONSTRAINT FK_REL_TURMAS__DISCIPLINAS_IDPROFESSOR FOREIGN KEY (IDPROFESSOR) REFERENCES CAD_PROFESSORES(IDPROFESSOR);

GO
